version: "3.7"

services:
  plantuml:
    image: plantuml/plantuml-server:v1.2022.4
    ports:
      - "5050:8080"

  db:
    environment:
      POSTGRES_USER: nsctool
      POSTGRES_PASSWORD: nsctool
      POSTGRES_DB: nsctool
    volumes:
      - "/opt/nsctool/db/data:/var/lib/postgresql"
  
  api:
    environment:
      ENV APP_DB_URL: jdbc:postgresql://db:5432/nsctool
      ENV APP_DB_USERNAME: nsctool
      ENV APP_DB_PASSWORD: nsctool
  
  db-web:
    image: dpage/pgadmin4:6
    restart: always
    networks:
      - db
    ports:
      - "7081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@implex1v.de
      PGADMIN_DEFAULT_PASSWORD: admin
