version: "3.7"

services:
  web:
    ports: ["7080:3000"]

  db:
    ports:
      - "5432:5432"

  plantuml:
    image: plantuml/plantuml-server:v1.2022.4
    ports:
      - "5050:8080"
  
  db-web:
    image: dpage/pgadmin4:6
    restart: always
    networks:
      - db
    ports:
      - "7081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@implex1v.de
      PGADMIN_DEFAULT_PASSWORD: admin
  
  keycloak:
    ports:
      - 8180:8180
    command:
      - start-dev
      - --http-port 8180
      - -Dkeycloak.migration.action=export 
      - -Dkeycloak.migration.provider=singleFile 
      - -Dkeycloak.migration.file=keycloak-backup.json
    volumes:
      - "./_data/keycloak/:/opt/keycloak/data/h2/"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
