version: "3.7"

x-buildargs: &build_args
  GIT_COMMIT: ${GIT_COMMIT:-'git-commit'}
  BUILD_VERSION: ${GITVERSION_SEMVER:-'semver'}

services:
  web:
    image: ${CR_BASE:-local}/nsctool-web:${GITVERSION_SEMVER:-latest}
    ports: ["7080:3000"]
    build:
      context: ./web/
      args:
        <<: *build_args
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: QMUr2DkBCE9PyYTJqrszTkVAhYShsHbL
      APP_AUTH_CLIENT_ID: web
      APP_AUTH_CLIENT_SECRET: a0l6upjfJP2RD54SC8F0lyy46fUZO0l1
      APP_AUTH_URL: http://keycloak:8180

  # this builds or runs api/Dockerfile
  api:
    # path of the builded docker image
    image: ${CR_BASE:-local}/nsctool-api:${GITVERSION_SEMVER:-latest}
    ports: ["8080:8080"]
    build: 
      # path, where the Dockerfile is
      context: ./api/
      # gives args for commit...
      args:
        <<: *build_args
    depends_on:
    - keycloak
    - db
    # overrides the evironment variables defined in the Dockerfile
    environment:
      APP_KEYCLOAK_ADMIN_BASEURI: http://keycloak:8180
      APP_DB_URL: jdbc:postgresql://db:5432/nsctool
      APP_DB_USERNAME: nsctool
      APP_DB_PASSWORD: nsctool
  
  db:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nsctool
      MONGO_INITDB_ROOT_PASSWORD: nsctool
      MONGO_INITDB_DATABASE: nsctool

  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    restart: unless-stopped
    command:
      - start
      - --http-port 8180
      - --hostname auth.${HOST:-localhost}
      - --proxy edge
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # DB_VENDOR: POSTGRES
      # DB_ADDR: db
      # DB_DATABASE: keycloak
      # DB_USER: keycloak
      # DB_SCHEMA: public
      # DB_PASSWORD: password
