version: "3.7"

services:
  plantuml:
    image: plantuml/plantuml-server:v1.2022.4
    ports:
      - "5050:8080"
  
  db-web:
    image: dpage/pgadmin4:6
    restart: always
    networks:
      - db
    ports:
      - "7081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@implex1v.de
      PGADMIN_DEFAULT_PASSWORD: admin
