@startuml server-deployment-traefik
skinparam monochrome true

frame "Deployment server setup with traefik" {
    node web {
    }

    node Server <<device>> {
        [ingress] <<nginx>>

        node Docker <<docker>> {
            [traefik] <<container>>
            [registry] <<container>>
            [portainer] <<container>>
        }

        ingress -r-> traefik : HTTP: *.cloud.example.com <<reverse proxy>>
        traefik -r-> registry : HTTP: registry.cloud.example.com
        traefik -r-> portainer : HTTP: portainer.cloud.example.com
        registry <--> portainer : docker.d
    }

    web -r-> ingress : HTTP: example.com
}



@enduml