@startuml server-deployment
skinparam monochrome true

frame "Deployment server setup with traefik" {
    node www {
    }

    node Server <<device>> {
        [ingress] <<nginx>>

        node Docker <<docker>> {
            [registry] <<container>>
            [portainer] <<container>>
            
            node nsctool <<docker-network>> {
                [traefik] <<container>>
                [web] <<container>>
                [api] <<container>>
            }

            traefik -r-> web : HTTP: web.nsctool.example.com
            traefik --> api : HTTP: api.nsctool.example.com
        }

        ingress -r-> traefik : <<reverse proxy>> \n HTTP: *.nsctool.example.com
        ingress -r-> registry : <<reverse proxy>> \n HTTP: registry.example.com
        ingress -r-> portainer : <<reverse proxy>> \n HTTP: portainer.example.com
        registry <--> portainer : docker.d
    }

    www -r-> ingress : HTTPS: example.com
}

@enduml
