spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/nsctool
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${APP_DB_PASSWORD:password}
    username: ${APP_DB_USERNAME:sa}
    url: ${APP_DB_URL:jdbc:h2:mem:phrasenschwein}
  h2:
    console:
      enabled: 'true'

server:
  error:
    whitelabel:
      enabled: 'false'

springdoc:
  swagger-ui:
    path: /doc/swagger
  api-docs:
    path: /doc/openapi.json

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

keycloak:
  admin:
    baseUri: http://localhost:8180
    realm: nsctool
    username: api-admin
    password: acSsYQMPh6bE2rTCKg4niHe6jW9NUWdw
    client:
      id: idm-client
      secret: efUD1vwp4VuVLzz999khJCIMZXV3nkMa
