spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/nsctool
#      client:
#        provider:
#          keycloak:
#            authorization-uri: http://localhost:8180/realms/nsctool/protocol/openid-connect/auth
#            token-uri: http://localhost:8180/realms/nsctool/protocol/openid-connect/token
#            jwk-set-uri: http://localhost:8180/realms/nsctool/protocol/openid-connect/certs
#            user-info-uri: http://localhost:8180/realms/nsctool/protocol/openid-connect/userinfo
#            user-name-attribute: user_name
#        registration:
#          keycloak:
#            client-id: api
#            client-secret: iC0nmgw7gz1Q8beOxYKFZl1mJ38iGrdy
#            scope: openid,profile
#            authorization-grant-type: password
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${APP_DB_PASSWORD:password}
    username: ${APP_DB_USERNAME:sa}
    url: ${APP_DB_URL:jdbc:h2:mem:phrasenschwein}
  h2:
    console:
      enabled: 'true'

server:
  error:
    whitelabel:
      enabled: 'false'

springdoc:
  swagger-ui:
    path: /doc/swagger
  api-docs:
    path: /doc/openapi.json

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
