spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_KEYCLOAK_ADMIN_BASEURI:http://localhost:8180}/realms/nsctool
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${APP_DB_PASSWORD:password}
    username: ${APP_DB_USERNAME:sa}
    url: ${APP_DB_URL:jdbc:h2:mem:phrasenschwein}
  h2:
    console:
      enabled: 'true'

server:
  error:
    whitelabel:
      enabled: 'false'

springdoc:
  swagger-ui:
    path: /doc/swagger
  api-docs:
    path: /doc/openapi.json

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

keycloak:
  admin:
    baseUri: ${APP_KEYCLOAK_ADMIN_BASEURI:http://localhost:8180}
    realm: ${APP_KEYCLOAK_ADMIN_REALM:nsctool}
    username: ${APP_KEYCLOAK_ADMIN_USERNAME:api-admin}
    password: ${APP_KEYCLOAK_ADMIN_PASSWORD:acSsYQMPh6bE2rTCKg4niHe6jW9NUWdw}
    client:
      id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID:idm-client}
      secret: ${APP_KEYCLOAK_ADMIN_CLIENT_SECRET:efUD1vwp4VuVLzz999khJCIMZXV3nkMa}
