spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_KEYCLOAK_ADMIN_BASEURI:http://localhost:8180}/realms/nsctool
  data:
    mongodb:
      authentication-database: ${APP_MONGO_AUTH_DATABASE:admin}
      username: ${APP_MONGO_USERNAME:nsctool}
      password: ${APP_MONGO_PASSWORD:nsctool}
      database: ${APP_MONGO_DATABASE:nsctool}
      port: ${APP_MONGO_PORT:27017}
      host: ${APP_MONGO_HOST:localhost}

server:
  error:
    whitelabel:
      enabled: 'false'

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health

keycloak:
  admin:
    baseUri: ${APP_KEYCLOAK_ADMIN_BASEURI:http://localhost:8180}
    realm: ${APP_KEYCLOAK_ADMIN_REALM:nsctool}
    username: ${APP_KEYCLOAK_ADMIN_USERNAME:api-admin}
    password: ${APP_KEYCLOAK_ADMIN_PASSWORD:acSsYQMPh6bE2rTCKg4niHe6jW9NUWdw}
    client:
      id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID:idm-client}
      secret: ${APP_KEYCLOAK_ADMIN_CLIENT_SECRET:efUD1vwp4VuVLzz999khJCIMZXV3nkMa}

security:
  enabled: ${APP_SECURITY_ENABLED:true}