apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6}}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s