name: _build

on:
  workflow_call:
    inputs:
      component:
        description: The component to build
        type: string
        required: true
      version:
        description: The current version
        type: string
        required: true
    secrets:
      cr:
        description: The container registry to use (default is GitHub)
        required: true
      cr_token:
        description: The container registry token
        required: true
      cr_user:
        description: The registry user
        required: true

defaults:
  run:
    shell: bash

env:
  COMPONENT: ${{ inputs.component }}

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CR_BASE: ${{ secrets.cr }}
      GITVERSION_SEMVER: ${{ inputs.version }}
      GIT_COMMIT: ${{ github.sha }}
      BUILD_VERSION: ${{ inputs.version }}
    steps:
      #------ 
      - uses: actions/checkout@v3
      # https://github.com/docker/login-action
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.cr }}
          username: ${{ secrets.cr_user }}
          password: ${{ secrets.cr_token }}
      - name: Build container image
        run: |
          docker-compose build ${COMPONENT}
          docker-compose push ${COMPONENT}
      - name: Retag to latest and push image
        run: |
          docker tag ${CR_BASE}/nsctool-${COMPONENT}:${BUILD_VERSION} ${CR_BASE}/nsctool-${COMPONENT}:latest
          docker push ${CR_BASE}/nsctool-${COMPONENT}:latest
