name: _deploy

on:
  workflow_call:
    inputs:
      stage:
        description: The stage to deploy to
        required: false
        type: string
        default: dev
    secrets:
      ssh_priv_key:
        description: The private ssh key to connect to the host
        required: true
      slack_webhook:
        description: The wslack webhook used for notifications
        required: true
      host:
        description: The host to deploy to
        required: true
      apiDbPassword:
        description: DB password for the database
        required: true
      cr:
        description: The cr host
        required: true
      app_keycloak_admin_realm:
        description: The cr host
        required: true
      app_keycloak_admin_username:
        description: The cr host
        required: true
      app_keycloak_admin_password:
        description: The cr host
        required: true
      app_keycloak_admin_client_id:
        description: The cr host
        required: true
      app_keycloak_admin_client_secret:
        description: The cr host
        required: true
      keycloak_admin:
        description: The cr host
        required: true
      keycloak_admin_password:
        description: The cr host
        required: true  

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: 
      group: deploy-dev
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v3
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      env:
        APP_KEYCLOAK_ADMIN_REALM: ${{ secrets.app_keycloak_admin_realm }}
        APP_KEYCLOAK_ADMIN_USERNAME: ${{ secrets.app_keycloak_admin_username }}
        APP_KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.app_keycloak_admin_password }}
        APP_KEYCLOAK_ADMIN_CLIENT_ID: ${{ secrets.app_keycloak_admin_client_id }}
        APP_KEYCLOAK_ADMIN_CLIENT_SECRET: ${{ secrets.app_keycloak_admin_client_secret }}
        KEYCLOAK_ADMIN: ${{ secrets.keycloak_admin }}
        KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.keycloak_admin_password }}
        CR: ${{ secrets.cr }}
        APP_HOST: ${{ secrets.host }}
        APP_API_DB_PASSWORD: ${{ secrets.api_db_password }}
      with:
        playbook: playbooks/update.yml
        directory: ./_devops/ansible
        requirements: requirements.yml
        # Optional, SSH private key of the machine
        key: ${{ secrets.ssh_priv_key }}
        # Optional, literal inventory file contents
        inventory: |
          [all]
          ${{ secrets.host }}
  
  slack:
    runs-on: ubuntu-20.04
    needs: ["deploy"]
    if: always() && needs.deploy.result == 'failure'
    steps:
    - name: notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
        SLACK_USERNAME: GitHub
        SLACK_MESSAGE: "Failed to deploy NSCTool on ${{ inputs.stage }} :cry: :pray:."
        SLACK_TITLE: Deployment failed
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        SLACK_COLOR: ${{ needs.deploy.result }}
