name: api-client/js
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "api-client/js/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  version:
    runs-on: ubuntu-20.04
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.x"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # For gitversion
      # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/index.md
      - id: gitversion
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
  
  build:
    needs:
      - version
    runs-on: ubuntu-20.04
    env:
      APP_VERSION: ${{ needs.version.outputs.semver }}
    steps:
      - uses: actions/checkout@v3
      - name: Install openapi-generator-cli
        run: |
          npm install @openapitools/openapi-generator-cli -g     
      - name: Generator client
        working-directory: ./api-client/js/
        run: |
          openapi-generator-cli generate \
            -g javascript \
            -o . \
            -i openapi.json \
            --additional-properties=projectName=@nsctool/api-client-js,npmVersion=${APP_VERSION},platform=browser,framework=fetch-api,licenseName=MIT,usePromises=true
      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (api-client/js) [generated] Release version ${{ needs.version.outputs.semver }}
          file_pattern: api-client/js/**
          commit_user_name: Npm bot
          skip_dirty_check: true 
      - name: npm build
        working-directory: ./api-client/js/
        run : |
          npm i
          npm run build
      # https://github.com/marketplace/actions/npm-publish
      - name: Push package to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: main
          token: ${{ secrets.NPM_TOKEN }}
          package: ./api-client/js/package.json
          access: public
