name: api-client/ts
on:
  push:
    branches:
      - main
    paths:
      - "api-client/ts/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  version:
    runs-on: ubuntu-20.04
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # For gitversion
      # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/index.md
      - id: gitversion
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
  
  build:
    needs:
      - version
    runs-on: ubuntu-20.04
    env:
      APP_VERSION: ${{ needs.version.outputs.semver }}
    steps:
      - uses: actions/checkout@v3
      - name: Install openapi-generator-cli
        run: |
          npm install @openapitools/openapi-generator-cli -g     
      - name: Generator client
        working-directory: ./api-client/ts/
        run: |
          openapi-generator-cli generate -g typescript -o . -i openapi.json --additional-properties=npmName=@nsctool/api-client-ts,npmRepository=https://github.com/Implex1v/NSCTool,npmVersion=${APP_VERSION}
      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (api-client/ts) [generated] Release version ${APP_VERSION}
          file_pattern: api-client/ts/**
          commit_user_name: NPM Bot   
      # https://github.com/marketplace/actions/npm-publish
      - name: Push package to npm
        working-directory: ./api-client/ts/
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: ${{ needs.version.outputs.semver }}
          token: ${{ secrets.NPM_TOKEN }}
