name: api
on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:
    
jobs:
  version:
    uses: Implex1v/NSCTool/.github/workflows/_version.yml@main
    with:
      component: api
    
  build:
    uses: Implex1v/NSCTool/.github/workflows/_build.yml@main
    needs:
    - version
    with:
      version: ${{ needs.version.outputs.version }}
      component: api
    secrets:
      cr: ${{ secrets.CR }}
      cr_token: ${{ secrets.GITHUB_TOKEN }}
      cr_user: ${{ secrets.CR_USER }}

  deploy:
    uses: Implex1v/NSCTool/.github/workflows/_deploy.yml@main
    needs:
    - version
    - build
    with:
      version: "${{ needs.version.outputs.version }}"
      component: api
    secrets:
      cr: ${{ secrets.CR }}
      cr_token: ${{ secrets.GITHUB_TOKEN }}
      cr_user: ${{ secrets.CR_USER }}
      domain: ${{ secrets.BASE_DOMAIN }}
      kube_config: ${{ secrets.KUBE_CONFIG }}
