#!/bin/bash

export NEXTAUTH_SECRET=${APP_WEB_NEXTAUTH_SECRET}
export APP_AUTH_URL=${APP_KEYCLOAK_ADMIN_BASEURI}
export APP_AUTH_CLIENT_ID=${APP_WEB_ADMIN_CLIENT_ID}
export APP_AUTH_CLIENT_SECRET=${APP_WEB_ADMIN_CLIENT_SECRET}

node index.js